inherit_from: .rubocop_todo.yml
# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
require:
  #  - rubocop-performance
  - rubocop-rails
    #- rubocop-rake
  - rubocop-rspec

# We want to relax the rules around specs/features and we don't want to worry about
# DB migrations at all:
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  DisabledByDefault: true
  Exclude:
    - features/**/*
    - db/migrate/*
    - vendor/**/*
    - bin/**/*

# Eliminate interpreter warnings; `ruby -w` should be clean:
Lint/DuplicateHashKey:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Security/Eval:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true

# Formatting options:
Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces
Layout/IndentationWidth:
  Enabled: true
  Width: 2
Layout/CaseIndentation:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
# We could probably shorten this further, but there are no lines longer
# than 206 characters and there are a lot of lines longer than 80 or 120:
Layout/LineLength:
  Enabled: true
  Max: 206
Layout/AssignmentIndentation:
  Enabled: true
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
Layout/RescueEnsureAlignment:
  Enabled: true

# Legibility:
Style/StringLiterals:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: true

